version: "3.5"

services:
  jekyll:
    image: ${IMAGE_NAME}
    build:
      context: ./
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t --watch

